#!/bin/sh
ssh root@wiredzenith.tech<<EOF
   cd /FallDetection
   git stash push --include-untracked
   git stash drop
   git pull
   cd Webpage/
   npm audit fix
   npm install
   cd ~
   pm2 restart all
   exit
EOF
