version: 2.1
working_directory: ~/Webpage/
orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout 
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test