version: 2.1

orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/Webpage
    steps:
      
      - checkout
      - node/with-cache:
          steps:
            - run: cd ~/Webpage/
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test